services:
  mysql:
    build:
      context: .
    volumes:
      - type: bind
        source: ./initdb.d
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=hoge
    ports:
      - target: 3306
        published: 4306
    tty: true
